version: "3.8"
services:
  app:
    # ビルドコンテキスト（docker build を実行する際の作業ディレクトリ/Dockerfile作成）
    build: ./infra/php
    # ホスト側:コンテナ側へマウント（Laravelをインストールするディレクトリ）
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.18-alpine
    # nginxにアクセスするポート(ホスト側:コンテナ側)
    ports:
      - 10080:80
    # ホスト側のディレクトリをコンテナ側にマウント
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./infra/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=laravel_local
      - MYSQL_USER=phper
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
    ports:
      - 13306:3306

  node:
    image: node:12.8-alpine
    volumes:
      - ./backend:/work
    working_dir: /work

volumes:
  db-store:
